import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryClientProvider } from "../shared/lib/ReactQueryClientProvider";
import { Header } from "@/widgets/header/ui/Header";
import { Footer } from "@/widgets/footer/Footer";
import { ReduxProvider } from "../shared/redux/Provider";

export const metadata: Metadata = {
  title: "Игрум",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <head>
        <link rel="icon" type="image/png" href="/3.png" />
      </head>
      <body className="flex flex-col min-h-screen">
        <ReduxProvider>
          <Header />
          <main className="flex-1 overflow-y-auto">
            <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
          </main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
